version: '3.9'

services:
  db_postgres:
    container_name: db_postgres
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data  # Volumen para persistir los datos
    ports:
      - "5432:5432"  # Mapea el puerto 5432 del host al contenedor
    restart: unless-stopped  # Asegura que el contenedor se reinicie si hay fallos

volumes:
  db_data:
