openapi: 3.0.0
info:
  title: Backend Integrador API
servers:
  - url: http://localhost:3000/api
    description: 'Servidor de desarrollo'

paths:
  /api/auth/register:
    post:
      description: Register to the application
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  description: nombre
                  example: "string"
                email:
                  type: string
                  description: email
                  example: "string"
                password:
                  type: string
                  description: password
                  example: "string"
                username:
                  type: string
                  description: username
                  example: "string"
                birthdate:
                  type: string
                  description: birthdate
                  example: "string"
      responses:
        '200':
          description: login
          content:
            application/json:
              schema:
                type: object
